"""
Supervisor Agent
Coordinates the diet and exercise agents for comprehensive recommendations
"""

from typing import Dict
from datetime import datetime
from langchain_openai import ChatOpenAI
from app.services.diet_agent import DietAgent
from app.services.exercise_agent import ExerciseAgent


class SupervisorAgent:
    """Supervisor that coordinates diet and exercise agents"""
    
    def __init__(self, llm: ChatOpenAI):
        self.llm = llm
        self.diet_agent = DietAgent(llm)
        self.exercise_agent = ExerciseAgent(llm)
    
    def generate_recommendations(self, body_type: str, goals: str, max_iterations: int = 2) -> Dict:
        """
        Generate comprehensive fitness recommendations
        
        Args:
            body_type: Body type (endomorph, ectomorph, mesomorph)
            goals: User's fitness goals
            max_iterations: Number of refinement iterations
            
        Returns:
            Dictionary with recommendations and markdown
        """
        state = {
            'body_type': body_type,
            'goals': goals,
            'current_iteration': 0,
            'max_iterations': max_iterations,
            'diet_recommendation': '',
            'exercise_recommendation': ''
        }
        
        # Iterate twice for refinement
        for iteration in range(max_iterations):
            state['current_iteration'] = iteration
            
            print(f"Starting iteration {iteration + 1}...")
            
            # Get diet recommendation
            print("Generating diet recommendation...")
            diet_rec = self.diet_agent.generate_recommendation(state)
            state['diet_recommendation'] = diet_rec
            
            # Get exercise recommendation
            print("Generating exercise recommendation...")
            exercise_rec = self.exercise_agent.generate_recommendation(state)
            state['exercise_recommendation'] = exercise_rec
        
        # Generate final markdown
        markdown = self._generate_markdown(state)
        
        return {
            'body_type': body_type,
            'goals': goals,
            'diet_recommendation': state['diet_recommendation'],
            'exercise_recommendation': state['exercise_recommendation'],
            'markdown': markdown,
            'generated_at': datetime.now().isoformat(),
            'duration': '4 weeks'
        }
    
    def _generate_markdown(self, state: Dict) -> str:
        """Generate markdown output"""
        body_type = state['body_type']
        goals = state['goals']
        diet = state['diet_recommendation']
        exercise = state['exercise_recommendation']
        
        markdown = f"""# Personalised 4-Week Fitness Plan

**Generated:** {datetime.now().strftime('%B %d, %Y')}
**Body Type:** {body_type.title()}
**Goals:** {goals}

---

## 🍽️ Diet Plan (4 Weeks)

{diet}

---

## 💪 Exercise Plan (4 Weeks)

{exercise}

---

## 📝 Notes

- This plan is designed for a {body_type} body type with a focus on: {goals}
- Follow this plan for 4 weeks
- Track your progress and adjust as needed
- Consult with a healthcare professional before starting any new diet or exercise program

---

## 🎯 Success Metrics

After 4 weeks, you should be able to see improvements in:
- Overall fitness and strength
- Energy levels
- Adherence to nutrition plan
- Progress toward your specific goals: {goals}

---

*Generated by AI Fitness App*
"""
        
        return markdown

